#! /usr/bin/env python

""" TODO

"""

import pathlib

import waves
import numpy
import SCons.Defaults

from model_package.Tardigrade_MOOSE import simulation_variables_nominal

# Inherit the parent construction environment
Import('env')

# set project-wide paths with os-agnostic path separators
Tardigrade_MOOSE_source_abspath = pathlib.Path(env["Tardigrade_MOOSE_source_abspath"])
mesh_templates_abspath = pathlib.Path(env["mesh_templates_abspath"])
model_package_abspath = pathlib.Path(env["model_package_abspath"])

# Simulation variables
build_directory = pathlib.Path(Dir('.').abspath)
workflow_name = build_directory.name
workflow_configuration = [env["project_configuration"], workflow_name]
output_file_type = "h5"
model = "elastic_convergence"
params = simulation_variables_nominal.elastic_cylinder

# Collect the target nodes to build a concise alias for all targets
workflow = []

parameter_schema = dict(
    parameter_samples = numpy.array([
        [192, 1.0, 1],
        [960, 0.5, 2],
        [2520, 0.375, 4],
        [7680, 0.25, 8]], dtype=object),
    parameter_names = numpy.array(["elements", "seed_size", "cpus"]))

parameter_generator = waves.parameter_generators.CustomStudy(parameter_schema)
for set_name, parameters in parameter_generator.parameter_study_to_dict().items():
    set_name = pathlib.Path(set_name)

    elements = parameters['elements']
    seed_size = parameters['seed_size']
    solve_cpus = parameters['cpus']

    # Copy template mesh
    seed_str = f"{str(seed_size).split('.')[0]}p{str(seed_size).split('.')[-1]}"
    mesh_copy = f"{params['mesh_copy_root']}_{seed_str}_{elements}_elements.e"
    tardi_mesh = f"TARDIGRADE-MOOSE_{model}_mesh_{elements}.e"
    workflow.extend(env.Command(
        target=[str(set_name / tardi_mesh)],
        source=[f"{mesh_templates_abspath}/{mesh_copy}"],
        action=SCons.Defaults.Copy("${TARGET}", "${SOURCE}", False)
        ))

    # Write elastic material card
    material_script = 'write_elastic_material_card.py'
    material_card = 'elastic_material_card.yml'
    E, nu = params['material_E'], params['material_nu']
    lamb = E*nu / ((1. + nu)*(1. - 2*nu))
    mu = E / (2*(1. + nu))
    script_options = f'--output-file {material_card}'
    script_options += f' --lamb {lamb}'
    script_options += f' --mu {mu}'
    workflow.extend(env.PythonScript(
        target=[str(set_name / material_card)],
        source=[str(Tardigrade_MOOSE_source_abspath / material_script)],
        script_options=script_options
        ))

    # build input file
    tardigrade_input_script = "build_Tardigrade_input_deck.py"
    tardi_sim_name = f'TARDIGRADE-MOOSE_{model}_{elements}'
    tardigrade_build_targs = f"{tardi_sim_name}.i"
    tardigrade_build_sources = [str(set_name / source) for source in [tardi_mesh, material_card]]
    script_options = f"--output-file {tardigrade_build_targs}"
    script_options += f" --parameter-sets {material_card}"
    script_options += f" --mesh {tardi_mesh}"
    script_options += f" --BCs {params['macro_BC']}"
    script_options += f" --disp {params['macro_disp']}"
    script_options += f" --duration {params['macro_duration']}"
    workflow.extend(env.PythonScript(
        target = [str(set_name / tardigrade_build_targs)],
        source = [f"{Tardigrade_MOOSE_source_abspath / tardigrade_input_script}", ],
        script_options = script_options
        ))
    tardigrade_build_sources.append(str(set_name / tardigrade_build_targs))

    # run Tardigrade-MOOSE
    tardigrade_moose_targs = [str(set_name / targ) for targ in [f'{tardi_sim_name}_out.e', f'{tardi_sim_name}_out.csv']]
    workflow.extend(env.TardigradeSolver(
        target = tardigrade_moose_targs,
        source = tardigrade_build_sources,
        tardigrade_program = env['Tardigrade'],
        tardigrade_input = tardigrade_build_targs,
        tardigrade_threads =  solve_cpus,
        stdout_file = f"{tardi_sim_name}_out.e.stdout"
        ))

    # plot force vs displacement
    output_csvs = []
    element_labels = []
    plot_script = "plot_force_displacement.py"
    plot_targets = [f"{tardi_sim_name}_force_displacement.png", f"{tardi_sim_name}_force_displacement.csv"]
    script_options = f"--csv-file {tardigrade_moose_targs[1].split('/')[-1]}"
    script_options += f" --output-file {plot_targets[0]}"
    script_options += f" --output-csv {plot_targets[1]}"
    script_options += f" --final-disp {params['macro_disp']}"
    workflow.extend(env.PythonScript(
        target=[str(set_name / targ) for targ in plot_targets],
        source=[str(Tardigrade_MOOSE_source_abspath / plot_script), tardigrade_moose_targs[-1]],
        script_options=script_options,
        ))
    output_csvs.append(str(set_name / plot_targets[1]))
    element_labels.append(elements)

# Summarize force vs displacements
summary_script = "summarize_micro_macro_force_displacements.py"
output_targets = [f"all_force_displacements.png", f"all_force_displacements.csv"]
plot_labels = [f'{element} elements' for element in element_labels]
script_options = f"--csv-files {' '.join(output_csvs)}"
script_options += f" --plot-labels {' '.join(plot_labels)}"
script_options += f" --output-file {output_targets[0]}"
script_options += f" --output-csv {output_targets[1]}"
workflow.extend(env.PythonScript(
    target=output_targets,
    source=[f"{Tardigrade_MOOSE_source_abspath / summary_script}"] + output_csvs,
    script_options=script_options
    ))

# Collector alias based on parent directory name
env.Alias(workflow_name, workflow)
